apiVersion: v1
kind: Service
metadata:
  name: nginx-service-dev   # Changed to avoid conflict
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
